version: 2

updates:
  - package-ecosystem: cargo
    directories:
      # Do NOT use "**/*", or `/wasm-bindgen-cli` will be included,
      # which breaks dependabot.
      - "/"
      - "/pgpvis-core"
    schedule:
      interval: weekly
    # Stop dependabot from spamming
    groups:
      cargo:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directories:
      - "**/*"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
