version: 2

updates:
  - package-ecosystem: npm
    directories:
      - "/"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
