name: Setup dependencies
description: Setup dependencies

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain cache
      id: cache-rust-toolchain
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
      with:
        path: ~/.rustup/toolchains/
        key: rust-toolchain-${{ hashFiles('./rust-toolchain.toml') }}
    - name: Setup Rust
      if: steps.cache-rust-toolchain.outputs.cache-hit != 'true'
      shell: bash
      run: |
        rustup toolchain install
    - name: Setup Rust dependency cache
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5  # v2.8.2

    # This has to be before `setup-node`.
    # See https://github.com/actions/setup-node/blob/49933ea5288caeca8642d1e84afbd3f7d6820020/docs/advanced-usage.md#caching-packages-data
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061  # v4.2.0
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
      with:
        node-version-file: .nvmrc
        cache: pnpm
    - name: Install pnpm dependencies
      shell: bash
      run: |
        pnpm i

    - name: Setup editorconfig-checker cache
      id: cache-editorconfig-checker
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
      with:
        path: /usr/local/bin/editorconfig-checker
        key: editorconfig-checker-fd130e0731d9f9dd3a31dfff594996bffc2d448677e74b6d2dfb10f8992d6c92
    - name: Setup editorconfig-checker
      if: steps.cache-editorconfig-checker.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd $(mktemp -d)
        wget https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.1/editorconfig-checker-linux-amd64.tar.gz
        echo "fd130e0731d9f9dd3a31dfff594996bffc2d448677e74b6d2dfb10f8992d6c92 editorconfig-checker-linux-amd64.tar.gz" | sha256sum --check
        tar xfzv editorconfig-checker-linux-amd64.tar.gz
        cp editorconfig-checker /usr/local/bin/
        chmod +x /usr/local/bin/editorconfig-checker
