cargo-features = ["trim-paths"]

[workspace]
resolver = "2"
members = [
    "pgpvis-core",
]

[profile.release]
opt-level = 0
strip = "none"
lto = "off"
panic = "abort"
incremental = false
codegen-units = 1
trim-paths = "all"
