[workspace]
resolver = "2"
members = [
    "pgpvis-core",
    "wasm-bindgen-cli",
]

[profile.release]
opt-level = "s"
strip = "symbols"
lto = true
panic = "abort"
incremental = false
codegen-units = 1
